version: "3.1"

services:
  mongo:
    image: mongo
    container_name: mongodb2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge

volumes:
  mongo_data:
